# Generated by Django 3.0.4 on 2020-03-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0008_remove_categoria_nome_filme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, verbose_name='Movie')),
                ('movie_url', models.TextField()),
                ('movie_img', models.TextField()),
                ('movie_sinopse', models.TextField()),
                ('movie_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
            ],
        ),
    ]
