# Generated by Django 3.0.4 on 2020-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_remove_filmes_categorias_filme'),
        ('categorias', '0002_categoria_nome_filme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_filme',
            field=models.ManyToManyField(blank=True, null=True, to='filmes.Filmes'),
        ),
    ]
