# Generated by Django 3.0.4 on 2020-03-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_auto_20200329_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nome_filme',
        ),
    ]
