# Generated by Django 3.0.4 on 2020-03-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_remove_filmes_categorias_filme'),
        ('categorias', '0006_remove_categoria_nome_filme'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome_filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmes.Filmes'),
        ),
    ]
