# Generated by Django 3.0.4 on 2020-03-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0007_categoria_nome_filme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nome_filme',
        ),
    ]
