# Generated by Django 3.0.3 on 2020-03-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filme', models.CharField(max_length=255, verbose_name='Filme')),
                ('url_filme', models.CharField(max_length=255, verbose_name='url')),
                ('sinopse_filme', models.TextField()),
                ('categorias_filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria', verbose_name='Categoria')),
            ],
        ),
    ]
