# Generated by Django 3.0.3 on 2020-03-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='img_filme',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='url_filme',
            field=models.TextField(),
        ),
    ]
