# Generated by Django 3.0.4 on 2020-03-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_filmes_categorias_filme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='categorias_filme',
        ),
    ]
