# Generated by Django 3.0.4 on 2020-03-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0008_remove_categoria_nome_filme'),
        ('filmes', '0005_remove_filmes_categorias_filme'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='categorias_filme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria'),
        ),
    ]
